//
//  JSONStructureConstant.h
//  demo
//
//  Created by Ashish Tiwari on 20/05/13.
//
//

#ifndef demo_JSONStructureConstant_h
#define demo_JSONStructureConstant_h


FOUNDATION_EXPORT NSString *const JsonStrucConst_TRUE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FALSE;

// dotForm
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_FORMS;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SCREEN_DESC;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SCREEN_NAME;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SCREEN_HEADER;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SCREEN_MENU_CONFIG;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM_SUB_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ADAPTER_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SUBMIT_ADAPTER_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_VIEW_ADAPTER_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM_ELEMENT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM;

FOUNDATION_EXPORT NSString *const JsonStrucConst_ELEMENTS;

// dotFormElement
FOUNDATION_EXPORT NSString *const JsonStrucConst_ELEMENT_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ELEMENT_POSITION;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DESCRIPTION;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DISPLAY_TEXT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_OPTIONAL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DATA_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_LENGTH;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DEFAULT_VAL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_IS_ELEMENT_DISPLAY;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ELEMENT_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_IS_HISTORY_CACHE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_IS_ELEMENT_DEPEND_ON_OTHER;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DEPENDED_ELEMENT_NAME;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DEPENDED_ELEMENT_VALUE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_VALUE_SET_ELEMENT_NAME;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORMAT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ELEMENT_STYLE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MASTER_VALUE_MAPPING;
FOUNDATION_EXPORT NSString *const JsonStrucConst_COLUMN_CONFIG;
FOUNDATION_EXPORT NSString *const JsonStrucConst_EXTENDED_PROPERTY;
FOUNDATION_EXPORT NSString *const JsonStrucConst_IS_USE_FORWARD;
FOUNDATION_EXPORT NSString *const JsonStrucConst_EXTENDED_PROPERTY;
FOUNDATION_EXPORT NSString *const JsonStrucConst_EVENT_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_READ_ONLY;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ENABLE_ALL;

// Constant for Report Definition other then Form Element and Definition
FOUNDATION_EXPORT NSString *const JsonStrucConst_PLACE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_VALUE_DEPEND_ON;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT_PLACES;
FOUNDATION_EXPORT NSString *const JsonStrucConst_IS_DRILL_DOWN;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DRILLDOWN_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT_ELEMENT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_REPORTS;


//Constant for the ClientMasterDetail
FOUNDATION_EXPORT NSString *const JsonStrucConst_USER_MODULE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MODULE_UPDATE_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MASTER_DATA_REFRESH;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MASTER_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_CLIENT_XML_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_FORM_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_REPORT_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_CLIENT_MASTER_DETAIL;

//Login Structure Property Constant
FOUNDATION_EXPORT NSString *const JsonStrucConst_USER_NAME;
FOUNDATION_EXPORT NSString *const JsonStrucConst_PASSWORD;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MODULE_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_LANGUAGE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ROLE_XML_CACHE_DATE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DEVICE_INFO_MAP;
FOUNDATION_EXPORT NSString *const JsonStrucConst_AUTH_TOKEN;


//Menu Detail Constant
FOUNDATION_EXPORT NSString *const JsonStrucConst_USER_LOGIN_STATUS;
FOUNDATION_EXPORT NSString *const JsonStrucConst_USER_LOGIN_MSG;
FOUNDATION_EXPORT NSString *const JsonStrucConst_PASS_STATE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_PASS_STATE_MSG;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MAX_DOC_NO;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SERVER_DATE_TIME;
FOUNDATION_EXPORT NSString *const JsonStrucConst_MENU_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_USER_DASHBOARD_DATA;


//Dot Form post Constant
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOC_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOC_DESC;
FOUNDATION_EXPORT NSString *const JsonStrucConst_ADAPTER_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_REPORT_CACHE_REFRESH;
FOUNDATION_EXPORT NSString *const JsonStrucConst_POST_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DISPLAY_DATA;

//DocPost Response
FOUNDATION_EXPORT NSString *const JsonStrucConst_TRACKER_NO;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SUBMIT_MESSAGE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SUBMIT_STATUS;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SUBMIT_DATA;

// Report Post Response Constant
FOUNDATION_EXPORT NSString *const JsonStrucConst_VIEW_REPORT_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_HEADER_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_TABLE_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SUB_HEADER_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FOOTER_DATA;

///DocFormPost Off line Processing Object
FOUNDATION_EXPORT NSString *const JsonStrucConst_STATUS_CLIENT_SUBMIT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_STATUS_SERVER_SUBMIT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_RECORD_STATUS;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOC_SUBMIT_DATE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_FORM_POST_RESPONSE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SERVER_RESPONSE_ID_ON_FIRST_SINK;
FOUNDATION_EXPORT NSString *const JsonStrucConst_DOT_FORM_POST_OBJ;

//Search Response Constant
FOUNDATION_EXPORT NSString *const JsonStrucConst_SEARCH_MESSAGE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SEARCH_HEADER_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SEARCH_DATA_FOR_SUBMIT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SEARCH_DATA_FOR_DISPLAY;
FOUNDATION_EXPORT NSString *const JsonStrucConst_SEARCH_RECORD;


// App Version update

FOUNDATION_EXPORT NSString *const JsonStrucConst_APP_UPDATE_MINOR_VERSION;
FOUNDATION_EXPORT NSString *const JsonStrucConst_APP_UPDATE_MAJOR_VERSION;
FOUNDATION_EXPORT NSString *const JsonStrucConst_APP_UPDATE_FORCE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_APP_UPDATE_APP_DOWNLOAD_URL;

//For the Register Notification Devices
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_DEVICE_REGISTER_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_DEVICE_PORT;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_APP_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_MODULE_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_SESSION_DETAIL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_USER_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_IMEI;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_OS;

//For the Send Comman Notfication Structure
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_OPERATION;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_IS_REQUIRE_LOGIN;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_IS_RESPOND_BACK;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_IS_APP_RESTART;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_IS_CONTENT_SEND_AS_BYTES;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_TYPE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_TITLE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_MSG;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_URL;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONTENT_CALL_BACK_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_EXTRA_INFO;

FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CREATE_DATE;
FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_LOG_ID;

//Common Request Send Request
FOUNDATION_EXPORT NSString *const JsonStrucConst_COMMON_REQ_REQUEST_ID;
FOUNDATION_EXPORT NSString *const JsonStrucConst_COMMON_REQ_POST_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_COMMON_REQ_EXTRA_DATA;
FOUNDATION_EXPORT NSString *const JsonStrucConst_COMMON_REQ_EXTRA_STRING;


FOUNDATION_EXPORT NSString *const JsonStrucConst_NOTIFY_CONFIG_ID;



#endif
