//
//  LanguageConstant.h
//  demo
//
//  Created by Ashish Tiwari on 20/05/13.
//
//

#ifndef demo_LanguageConstant_h
#define demo_LanguageConstant_h

FOUNDATION_EXPORT NSString *const LangConst_PREFIX;
FOUNDATION_EXPORT NSString *const LangConst_WRITE_AS;
FOUNDATION_EXPORT NSString *const LangConst_CHANGE_LANGUAGE;
FOUNDATION_EXPORT NSString *const LangConst_LANG_NAME;
FOUNDATION_EXPORT NSString *const LangConst_USER_NAME;
FOUNDATION_EXPORT NSString *const LangConst_PASSWORD;
FOUNDATION_EXPORT NSString *const LangConst_LOGIN;
FOUNDATION_EXPORT NSString *const LangConst_BACK;
FOUNDATION_EXPORT NSString *const LangConst_EXIT_APP;
FOUNDATION_EXPORT NSString *const LangConst_SUBMIT;
FOUNDATION_EXPORT NSString *const LangConst_MAIN_MENU;
FOUNDATION_EXPORT NSString *const LangConst_MENU;
FOUNDATION_EXPORT NSString *const LangConst_HOME;
FOUNDATION_EXPORT NSString *const LangConst_PLEASE;
FOUNDATION_EXPORT NSString *const LangConst_PLEASE_SELECT;
FOUNDATION_EXPORT NSString *const LangConst_PLEASE_PROVIDE;
FOUNDATION_EXPORT NSString *const LangConst_PLEASE_ENTER;
FOUNDATION_EXPORT NSString *const LangConst_AT_LEAST;
FOUNDATION_EXPORT NSString *const LangConst_CONTACT_ADMIN;
FOUNDATION_EXPORT NSString *const LangConst_NOT_CONFIGURED;
FOUNDATION_EXPORT NSString *const LangConst_NOT_DEFINED;
FOUNDATION_EXPORT NSString *const LangConst_VALID;
FOUNDATION_EXPORT NSString *const LangConst_HRS;
FOUNDATION_EXPORT NSString *const LangConst_MINUTE;
FOUNDATION_EXPORT NSString *const LangConst_SELECT;
FOUNDATION_EXPORT NSString *const LangConst_SEARCH;
FOUNDATION_EXPORT NSString *const LangConst_DELETE;

FOUNDATION_EXPORT NSString *const LangConst_INSERT;
FOUNDATION_EXPORT NSString *const LangConst_CANCEL;
FOUNDATION_EXPORT NSString *const LangConst_RE_SUBMIT;
FOUNDATION_EXPORT NSString *const LangConst_NULL ;
FOUNDATION_EXPORT NSString *const LangConst_OK;
FOUNDATION_EXPORT NSString *const LangConst_CONFIRM_PASS;
FOUNDATION_EXPORT NSString *const LangConst_APPLICATION_DOWNLOAD_ERROR;
FOUNDATION_EXPORT NSString *const LangConst_CONNECTION_ERROR;
FOUNDATION_EXPORT NSString *const LangConst_CONNECTION_ERROR_FATAL;
FOUNDATION_EXPORT NSString *const LangConst_CONNECTION_TIMEOUT;
FOUNDATION_EXPORT NSString *const LangConst_PERMISSION_ERROR;
FOUNDATION_EXPORT NSString *const LangConst_SERVICE_ERROR_TIMEOUT;
FOUNDATION_EXPORT NSString *const LangConst_SERVICE_ERROR;
FOUNDATION_EXPORT NSString *const LangConst_USER_CANCEL;
FOUNDATION_EXPORT NSString *const LangConst_ERROR;
FOUNDATION_EXPORT NSString *const LangConst_AUTHORIZATION_CODE;
FOUNDATION_EXPORT NSString *const LangConst_OPTIONS;
FOUNDATION_EXPORT NSString *const LangConst_YES;
FOUNDATION_EXPORT NSString *const LangConst_NO;
FOUNDATION_EXPORT NSString *const LangConst_SUBMIT_ORDER_CONFIRM;
FOUNDATION_EXPORT NSString *const LangConst_SUBMIT_DOC_CONFIRM;
FOUNDATION_EXPORT NSString *const LangConst_DOC_SUBMIT_RESPONSE;
FOUNDATION_EXPORT NSString *const LangConst_ANS;
FOUNDATION_EXPORT NSString *const LangConst_UPDATE;
FOUNDATION_EXPORT NSString *const LangConst_LIST;
FOUNDATION_EXPORT NSString *const LangConst_DELETE_RECORD_CONFIRM;

#endif
