//
//  XmwcsConstant.h
//  QCMSProject
//
//  Created by Ashish Tiwari on 20/05/13.
//  Copyright (c) 2013 dotvik. All rights reserved.
//

#ifndef QCMSProject_XmwcsConstant_h
#define QCMSProject_XmwcsConstant_h

//application modules
FOUNDATION_EXPORT NSString *const XmwcsConst_APP_MODULE_ESS; 
FOUNDATION_EXPORT NSString *const XmwcsConst_APP_MODULE_SALES; 
FOUNDATION_EXPORT NSString *const XmwcsConst_APP_MODULE_WORKFLOW; 




FOUNDATION_EXPORT int const XmwcsConst_SORT_AS_INTEGER ;
FOUNDATION_EXPORT int const XmwcsConst_SORT_AS_STRING;
//    public static final LoginRequestProcessUtil LOGIN_REQUEST_PROCESS_UTIL = new LoginRequestProcessUtil();
//    public static final ComponetDraw COMPONET_DRAW = new ComponetDraw();
//

FOUNDATION_EXPORT NSString *const  XmwcsConst_FORGOT_PWD_USER_ID;   // = @"USER_ID";
FOUNDATION_EXPORT NSString *const  XmwcsConst_FORGOT_PWD_MODULE_ID;  // = @"MODULE_ID";

FOUNDATION_EXPORT NSString* XmwcsConst_SERVICE_URL;   // = "http://localhost:8080/xmwcs/feed";
FOUNDATION_EXPORT NSString* XmwcsConst_SERVICE_URL_NOTIFY_CONTEXT;
FOUNDATION_EXPORT NSString* XmwcsConst_SERVICE_UPDATE_DROPDOWM_URL_NOTIFY_CONTEXT;
FOUNDATION_EXPORT NSString* XmwcsConst_SERVICE_URL_APP_CONTROL;
FOUNDATION_EXPORT NSString* XmwcsConst_PRODUCT_TREE_SERVICE_URL;
FOUNDATION_EXPORT NSString* XmwcsConst_SERVICE_URL_DEAL_STORE;


FOUNDATION_EXPORT NSString*  XmwcsConst_CHAT_URL;
FOUNDATION_EXPORT NSString*  XmwcsConst_OPCODE_URL; //for opcode Service Hit
FOUNDATION_EXPORT NSString*  XmwcsConst_FILE_UPLOAD_URL; //for file upload url
FOUNDATION_EXPORT NSString*  XmwcsConst_DEALER_OPCODE_URL;

FOUNDATION_EXPORT NSString *const XmwcsConst_DEMO_USER;
FOUNDATION_EXPORT NSString *const XmwcsConst_DEMO_USER_MAPPED;

FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_NOTIFY_CONTEXT_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_PRODUCT_TREE_SERVICE_URL_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_APP_CONTROL_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_DEAL_STORE_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_OPCODE_SERVICE_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_FILE_UPLOAD_SERVICE_PROD;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_CHAT_SERVICE_PROD;
FOUNDATION_EXPORT NSString* const XmwcsConst_DEALER_OPCODE_URL_PROD;

FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_NOTIFY_CONTEXT_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_PRODUCT_TREE_SERVICE_URL_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_APP_CONTROL_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_DEAL_STORE_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_OPCODE_SERVICE_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_FILE_UPLOAD_SERVICE_DEMO;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_CHAT_SERVICE_DEMO;
FOUNDATION_EXPORT NSString* const XmwcsConst_DEALER_OPCODE_URL_DEMO;

FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_NOTIFY_CONTEXT_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_PRODUCT_TREE_SERVICE_URL_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_APP_CONTROL_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_DEAL_STORE_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_OPCODE_SERVICE_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_FILE_UPLOAD_SERVICE_DEV;
FOUNDATION_EXPORT NSString *const XmwcsConst_SERVICE_URL_CHAT_SERVICE_DEV;
FOUNDATION_EXPORT NSString* const XmwcsConst_DEALER_OPCODE_URL_DEV;


FOUNDATION_EXPORT NSString *const XmwcsConst_HAVELLS_TRAVELLER_URL;
FOUNDATION_EXPORT NSString *const  XmwcsConst_MKONNECT_FAQ_URL;   // = @"http://mkonnect.havells.com:8080/xmwcshavells/faq.html";

//for the CALL NAME
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_LOGIN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_SUBMIT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_REPORT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_SEARCH ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_SEARCH_MASTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_CHANGE_PASSWORD;// = "FOR_CHANGE_PASSWORD";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_FORGOT_PASSWORD;// = "FOR_FORGOT_PASSWORD";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_UPDATE_APP_VERSION; // = @"FOR_UPDATE_APP_VERSION";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_NOTIFY_DEVICE_REGISTER; // = @"FOR_NOTIFY_DEVICE_REGISTER";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_FETCH_NOTIFICATION_LIST; // for fetching pending notifications
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_NOTIFY_DEVICE_DEREGISTER; // = @"FOR_NOTIFY_DEVICE_DEREGISTER";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_NOTIFY_PUSH_SEND_RES; // = @"FOR_NOTIFY_PUSH_SEND_RES";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_NOTIFY_PUSH_SEND; // = @"FOR_NOTIFY_PUSH_SEND";
FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_COMMON_REQUEST; // = @"FOR_COMMON_REQUEST";

FOUNDATION_EXPORT NSString *const XmwcsConst_CALL_NAME_FOR_VIEW_EDIT;   // for view edit type

//Component Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_SUGGESTIVE_SEARCH_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_TEXTFIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_TEXTAREA ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_DISABLED_TEXTFIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_LABEL;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_DROPDOWN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_EDITABLE_DROPDOWN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_BUTTON ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_CHECKBOX ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_RADIO_GROUP ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_DATE_FIELD;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_TIME_FIELD;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_CONTACT_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_EMAIL_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_SUBHEADER_GROUP ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_PHONE_NO_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_SEARCH_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_CHECKBOX_GROUP ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_TEXTFIELD_PASSWORD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_SUB_HEADER;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_MULTI_SELECT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_MULTI_SELECT_SEARCH;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_EDIT_SEARCH_FIELD;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_BARCODE_SCAN_FIELD;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_ATTACHMENT_BUTTON;

FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_LOCATION;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_CAMERA_IMAGE;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COMPONENT_CAMERA_VIDEO;



//dot Form Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_SIMPLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_ADD_ROW ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_BUTTON ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_SIMPLEADDROW;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_SIMPLEADDROW_SAMEFORM;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_ABOUT_US ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_FAQ ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_OTHER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_CHANGE_PASSWORD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_FILE_EXPLORER;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_NOTIFICATION;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_TYPE_POINTS;


//boolean Value
FOUNDATION_EXPORT NSString *const XmwcsConst_BOOLEAN_VALUE_TRUE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_BOOLEAN_VALUE_FALSE;

//Dropdown Value Pattern
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DD_VALUE_PTRN_CODE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DD_VALUE_PTRN_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DD_VALUE_PTRN_CODE_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DD_VALUE_PTRN_NAME_CODE;

//Time Field Value Pattern
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TIME_VALUE_PTRN_12HRS ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TIME_VALUE_PTRN_24HRS ;

//Button Data Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_ADD_ROW ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_FORM_SUBMIT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_CANCEL ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_VIEW_REPORT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_CALCULATE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_NEXT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_SUBFORM ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_BUTTON_DATA_TYPE_SEARCH;
//Text Data Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TEXTFIELD_DATA_TYPE_CHAR;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TEXTFIELD_DATA_TYPE_NUMERIC ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TEXTFIELD_DATA_TYPE_AMOUNT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TEXTFIELD_DATA_TYPE_FLOAT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_TEXTFIELD_DATA_TYPE_PHONE;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_LABEL_PREVIOUS_SCREEN;

FOUNDATION_EXPORT NSString *const XmwcsConst_DE_SEARCH_GROUP;



//Dot Element Date Fromat as
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_FORMAT_dd_MM_yyyy;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_FORMAT_yyyy_MM_dd;


//Dot Element Date View as
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_VIEW_IN_NATIVE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_VIEW_IN_CALENDAR ;

//Dot Report type
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_TYPE_SIMPLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_TYPE_SIMPLE_LINK;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_TYPE_LEGEND;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_TYPE_OTHER ;

//Dot Report Element Column Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_SIMPLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_COLOR  ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_HIDDEN  ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_CLICK  ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_COLOR_CLICK ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_EXPAND  ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_SPEC_CHAR_IND;  //= "SPEC_CHAR_IND";
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_CURRENT_DATE_TIME; // = "CURRENT_DATE_TIME";
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_URL;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_LABEL; //  = @"LABEL";
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_COLUMN_TYPE_CUSTOM_COLUMN; //  = @"CUSTOM_COLUMN";



//Dot Report Palces
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_HEADER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_FOOTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_SUBHEADER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_TABLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_HEADER$FOOTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_HEADER$TABLE;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_TABLE$FOOTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_HEADER$TABLE$FOOTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACE_HEADER$SUBHEADER$TABLE$FOOTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_PLACES_HEADER$SUBHEADER$TABLE ;


//DoC Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_SUBMIT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_VIEW ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_RECENT_REPORT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_CONTENT_FORM ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_LOGOUT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_VIEWDIRECT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_VIEWDIRECT_EDIT;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_URL_LAUNCH ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_EMAIL_LAUNCH;
FOUNDATION_EXPORT NSString *const XmwcsConst_DOC_TYPE_VIEW_EDIT;


//For the Dot Report Element Data Type
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_CHAR ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_NUMERIC ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_QUANTITY ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_AMOUNT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_MOBILE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DRE_DATA_TYPE_EMAIL ;
//For the menu map constant
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_FORM_ID ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_FORM_TYPE;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_IS_OPERATION_AVAL ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_OPERATION_DETAIL ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_OPERATION_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_SEQUENCE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_MENU_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_MENU_CONSTANT_LAST_FORM_ID;

//For the style movement
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_LABEL_MULTILINE;
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_LABEL_TICKER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_LABEL_NEWLINE ;

//For the style Alignment
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_PREOPERTY_LINE;   //  = "LINE";
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_PREOPERTY_ALIGNMENT; //  = "ALIGNMENT";
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_ALIGNMENT_HECNTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_ALIGNMENT_VCENTER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_ALIGNMENT_RIGHT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_STYLE_ALIGNMENT_LEFT ;


//Form Opertaions
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_CREATE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_UPDATE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_DELETE;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_LIST ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_FILTER_LIST ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_FILTER_UPDATE;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_FORM_OPERATION_FILTER_DELETE ;

//Dot Form Extended Property
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_EXTENDED_PROPERTY_SUB_GROUP ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_EXTENDED_PROPERTY_TABLE_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DF_EXTENDED_PROPERTY_ADD_ROW_COLUMN ;



//Dot Element Extended Property
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EXTENDED_PROPERTY_SUB_GROUP ;


//PHONE FIELD Constant
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_PHONE_FIRST_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_PHONE_LAST_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_PHONE_EMAIL ;

//Date FIELD Default Constant
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_DEFAULT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_LOWER_LIMIT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_DATE_UPPER_LIMIT ;
//Add Row Column Config
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COLUMN_NAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COLUMN_LENGTH ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_COLUMN_STYLE ;


//Expected value of EventDetail of Form Element
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_DETAIL_EVENT_TYPE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_DETAIL_REFRESH_FIELD ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_DETAIL_EVENT_ACTION ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_EVENT_LOST_FOCUS ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_EVENT_GOT_FOCUS ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_EVENT_ON_SELECT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_EVENT_ON_CLICK ;
FOUNDATION_EXPORT NSString *const XmwcsConst_DE_EVENT_EVENT_ALERT_WINODW ;

FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_TYPE_STRING ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_TYPE_INTEGER ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_TYPE_FLOAT ;

FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_TYPE_DOT_FORM_FIELD ;

FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_ADDITION ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_SUBSTRACTION ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_MULTIPLICATION ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_DIVISION ;

FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_GREATER_THAN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_GREATER_THAN_EQUAL ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_LESS_THAN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_LESS_THAN_EQUAL ; 
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_EQUAL ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_STRING_CONCAT ;

FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_RESULT_VALID ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_RESULT_NOT_VALID ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_RESULT_GT ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_RESULT_LESS ;
FOUNDATION_EXPORT NSString *const XmwcsConst_FIELD_OPERATION_RESULT_EQUAL ;


FOUNDATION_EXPORT int const XmwcsConst_SplashScreen;
FOUNDATION_EXPORT int const XmwcsConst_LaunchForm;
FOUNDATION_EXPORT int const XmwcsConst_LoginScreen;
FOUNDATION_EXPORT int const XmwcsConst_MainMenuScreen;
FOUNDATION_EXPORT int const XmwcsConst_EssMenuScreen;
FOUNDATION_EXPORT int const XmwcsConst_EssRecentRequestScreen; 
FOUNDATION_EXPORT int const XmwcsConst_EssRecentDocumentScreen;
FOUNDATION_EXPORT int const XmwcsConst_SalesMenuScreen;
FOUNDATION_EXPORT int const XmwcsConst_WorkflowLoginScreen;
FOUNDATION_EXPORT int const XmwcsConst_WorkflowMainScreen;
FOUNDATION_EXPORT int const XmwcsConst_SCREEN_ID_SIMPLE_FORM;
FOUNDATION_EXPORT int const XmwcsConst_SCREEN_ID_SEARCH_RESULT;
FOUNDATION_EXPORT int const XmwcsConst_SubMenuScreen;




FOUNDATION_EXPORT int const XmwcsConst_CommandExit;
FOUNDATION_EXPORT int const XmwcsConst_CommandBack ;
FOUNDATION_EXPORT int const XmwcsConst_CommandAbout;
FOUNDATION_EXPORT int const XmwcsConst_CommandCancel;
FOUNDATION_EXPORT int const XmwcsConst_CommandLogout;

FOUNDATION_EXPORT NSString *const XmwcsConst_CommandTextBack ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CommandTextExit ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CommandTextCancel ;
FOUNDATION_EXPORT NSString *const XmwcsConst_CommandTextLogout;

FOUNDATION_EXPORT NSString *const XmwcsConst_LaunchForm_APP_TITLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_LaunchForm_LOGIN ;
FOUNDATION_EXPORT NSString *const XmwcsConst_LoginScreen_TITLE ;
FOUNDATION_EXPORT NSString *const XmwcsConst_LoginScreen_USERNAME ;
FOUNDATION_EXPORT NSString *const XmwcsConst_LoginScreen_PASSWORD;
FOUNDATION_EXPORT NSString *const XmwcsConst_LoginScreen_SIGN_IN ;

FOUNDATION_EXPORT NSString *const XmwcsConst_MainMenuScreen_TITLE;
FOUNDATION_EXPORT NSString *const XmwcsConst_SIMPLESCREEN_TITLE;

FOUNDATION_EXPORT BOOL const XmwcsConst_IS_DEBUG;

FOUNDATION_EXPORT NSString *const XmwcsConst_IMEI;
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_MODEL;
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_DETAIL;


FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_MAX_DOC_ID;
FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_DOC_NAME;
FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_STATUS;
FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_TRACER_NO;
FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_DOC_SUBMIT_DATE;
FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_DOC_SUBMIT_MESSAGE;

FOUNDATION_EXPORT NSString *const XmwcsConst_RECENT_REQ_FORM_ID;

//For the Property of DrillDown Property
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_ADAPTER_ID;// = "ADAPTER_ID";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_ADAPTER_TYPE;// = "ADAPTER_TYPE";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_CALL_NAME;// = "CALL_NAME";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_MIDDLE_SCR_MSG;// = "MIDDLE_SCR_MSG";
FOUNDATION_EXPORT NSString *const XmwcsConst_DD_PROP_NETWORK_FIELD_TABLE;// = "NETWORK_FIELD_TABLE";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_NETWORK_FIELD_HEADER;// = "NETWORK_FIELD_HEADER";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_NETWORK_FIELD_FOOTER;// = "NETWORK_FIELD_FOOTER";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_IS_NETWORK_CALL;// = "IS_NETWORK_CALL";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_IS_DISPLAY_ON_EXPAND;// = "IS_DISPLAY_ON_EXPAND";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_URL_FIELD; // = "URL_FIELD"
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_ACTION;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_ACTION_TYPE;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_ACTION_FORM_ID;
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_DD_PROP_SERVER_CACHE;


//Extended  Poperty Of The Report

FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_EXTENDED_CLICK_EVENT_ON;// = "CLICK_EVENT_ON";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_EXTENDED_LEGEND_COLOR_ON;// = "LEGEND_COLOR_ON";
FOUNDATION_EXPORT NSString *const XmwcsConst_REPORT_EXTENDED_LEGEND_NAME_ON;// = "LEGEND_NAME_DATA_ON";





// error tags

FOUNDATION_EXPORT NSString *const XmwcsConst_MAIN_ERROR_TYPE; // = @"ERROR_TYPE";
FOUNDATION_EXPORT NSString *const XmwcsConst_MAIN_ERROR_SUB_TYPE; // = @"ERROR_SUB_TYPE";
FOUNDATION_EXPORT NSString *const XmwcsConst_MAIN_ERROR_MSG; // = @"ERROR_MSG";

//Main Exception Type

FOUNDATION_EXPORT int const XmwcsConst_MAIN_XMW_PLATFORM; // = 1;
FOUNDATION_EXPORT int const XmwcsConst_MAIN_ADAPTER; // = 2;
FOUNDATION_EXPORT int const XmwcsConst_MAIN_CLIENT; // = 3;


//Exception Sub type

FOUNDATION_EXPORT int const XmwcsConst_SUB_CLIENT_JSON_PARSE; // = 1;
FOUNDATION_EXPORT int const XmwcsConst_SUB_CLIENT_SERVICE_UN_AVAILABLE; // = 2;
FOUNDATION_EXPORT int const XmwcsConst_SUB_CLIENT_SESSION_EXPIRE; // = 3;
FOUNDATION_EXPORT int const XmwcsConst_SUB_CLIENT_PASSWORD_RESET; // = 4;
FOUNDATION_EXPORT int const XmwcsConst_SUB_CLIENT_OTHER; // = 5;


FOUNDATION_EXPORT int const XmwcsConst_SUB_XMW_PLATFORM_HIBERNATE; // = 6;
FOUNDATION_EXPORT int const XmwcsConst_SUB_XMW_PLATFORM_OTHER; // = 7;

FOUNDATION_EXPORT int const XmwcsConst_SUB_ADAPTER_CONNECTION_ERROR; // = 8;
FOUNDATION_EXPORT int const XmwcsConst_SUB_ADAPTER_DATA_PARSE_ERROR; // = 9;
FOUNDATION_EXPORT int const XmwcsConst_SUB_ADAPTER_OTHER; // = 10;

FOUNDATION_EXPORT NSString *const XmwcsConst_APP_ID; // = @"APP_ID";
FOUNDATION_EXPORT NSString *const XmwcsConst_APP_VERSION; // = @"APP_VERSION"
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE;  // = @"DEVICE_TYPE";

FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_ANDROID; // = @"Android";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_WINDOWS_PHONE; // = @"Windows Phone";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_J2ME; // = @"J2ME";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_BB10; // = @"BB10";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_BB; // = @"BB";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_IPHONE; // = @"iPhone";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_IPAD; //  = @"iPad";
FOUNDATION_EXPORT NSString *const XmwcsConst_DEVICE_TYPE_BROWSER; //  = @"Browser";

FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_OTHERS; //  = 0;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_MSG_WINDOW; // = 1;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_CONTENT; // = 2;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_FORM; // = 3;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_REPORT; // = 4;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_MENU_MSG; // = 5;//Total Sales
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_MENU_DATA; // = 6;
FOUNDATION_EXPORT int const XmwcsConst_NOTIFY_TYPE_URL_LAUNCH; // = 7;


//Keychain and AppGroup Identifier
FOUNDATION_EXPORT NSString *const XmwcsConst_KEYCHAIN_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_APPGROUP_IDENTIFIER;

//Dashboard Card Cell Observer Identifier
FOUNDATION_EXPORT NSString *const XmwcsConst_DASHBOARD_FOREGROUND_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_SALESAGGREGATE_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_CREDITDETAILS_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_ORDERPENDENCY_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_OVERDUE_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_NATIONALSALESAGGREGATE_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_NATIONALSALESAGGREGATEPIE_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_PAYMENTOUTSTANDING_CARD_AUTOREFRESH_IDENTIFIER;
FOUNDATION_EXPORT NSString *const XmwcsConst_OVERDUEPIE_CARD_AUTOREFRESH_IDENTIFIER;


//GPS Location Key
FOUNDATION_EXPORT NSString *const XmwcsConst_GPS_LOCATION_KEY;
FOUNDATION_EXPORT NSString *const XmwcsConst_GPS_LOCATION_LATITUDE_KEY;
FOUNDATION_EXPORT NSString *const XmwcsConst_GPS_LOCATION_LONGITUDE_KEY;
FOUNDATION_EXPORT NSString *const XmwcsConst_GPS_LOCATION_GET_CURRENT_TIME_KEY;
FOUNDATION_EXPORT           double XmwcsConst_GPS_LOCATION_GET_DEFAULT_TIME_VARIABLE;
FOUNDATION_EXPORT NSString *const XmwcsConst_ATTENDANCE_USER_DEFAULT_DICT;


#endif
